postgis:
    build: Dockerfiles/postgis/
    hostname: postgis
    container_name: postgis
    ports:
        - "5433:5432"
    volumes:
        - ./postgres_data:/var/lib/postgresql
    net: imiogeonode

rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    net: imiogeonode

geoserver:
    build: Dockerfiles/geoserver/
    hostname: geoserver
    container_name: geoserver
    ports:
        - 8080:8080
    environment:
        - JAVA_OPTS='-Xmx1g'
        - Xmx=2048M
        - XX:MaxPermSize=256M
    volumes:
        - ./geoserver_data:/opt/geoserver/data_dir
    net: imiogeonode

# NOTES:
#   - The C_FORCE_ROOT variable allows celery to run as the root user.
surveyworker:
    build: .
    environment:
        - C_FORCE_ROOT=true
    #hostname: geonode-worker
    #scontainer_name: geonode-worker
    volumes:
        - .:/opt/imio_geonode/
    entrypoint:
        - /usr/bin/python
    command: manage.py celery worker -E -lINFO
    net: imiogeonode

geonode:
    build: .
    environment:
        - C_FORCE_ROOT=true
    hostname: geonode
    container_name: geonode
    ports:
        - 8000:8000
    volumes:
        - .:/opt/imio_geonode/
    entrypoint:
        - /usr/bin/python
    command: manage.py runserver 0.0.0.0:8000
    net: imiogeonode


nginx:
    build: Dockerfiles/nginx/
    net: imiogeonode
    ports:
        - 80:80
#    links:
#        - geonode
#        - geoserver
#        - postgis
