ambassador:
    image: cpuguy83/docker-grand-ambassador
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    command: "-name imiogeonodegeonode1 -name imiogeonodegeoserver1"

postgis:
    image: mdillon/postgis
    hostname: postgis
    volumes:
        - ./postgres_data:/var/lib/postgresql
    environment:
         - USERNAME=postgres
         - PASS=postgres
geoserver:
    build: geoserver/
    hostname: geoserver
    links:
        - postgis
        - ambassador:imiogeonodegeonode1
    ports:
        - 8080:8080
    volumes:
        - ./geoserver_data:/opt/geoserver/data_dir
geonode:
    build: .
    hostname: geonode
    links:
        - postgis
        - ambassador:imiogeonodegeoserver1
    ports:
        - 8000:8000
    volumes:
        - .:/opt/imio_geonode/
