postgis:
    build: Dockerfiles/postgis/
    hostname: postgis
    container_name: postgis
    volumes:
        - ./postgres_data:/var/lib/postgresql
    net: imiogeonode
geoserver:
    build: Dockerfiles/geoserver/
    hostname: geoserver
    container_name: geoserver
    ports:
        - 8080:8080
    environment:
        - JAVA_OPTS='-Xmx1g'
        - Xmx=2048M
        - XX:MaxPermSize=256M
    volumes:
        - ./geoserver_data:/opt/geoserver/data_dir
    net: imiogeonode

geonode:
    build: .
    hostname: geonode
    container_name: geonode
    ports:
        - 8000:8000
    volumes:
        - .:/opt/imio_geonode/
    entrypoint:
        - /usr/bin/python
    command: manage.py runserver 0.0.0.0:8000
    net: imiogeonode

# nginx:
#     image: nginx:latest
#     ports:
#         - 80:80
#     links:
#         - geonode
#         - geoserver
#         - postgis
#     volumes:
#         - nginx-default.conf:/etc/nginx/conf.d/default.conf
