postgis:
    image: mdillon/postgis
    hostname: postgis
    volumes:
        - ./postgres_data:/var/lib/postgresql
    environment:
         - USERNAME=postgres
         - PASS=postgres
geoserver:
    build: geoserver/
    hostname: geoserver
    links:
        - postgis:postgres
        - geonode
    ports:
        - 8080:8080
    volumes:
        - ./geoserver_data:/opt/geoserver/data_dir
geonode:
    build: .
    hostname: geonode
    links:
        - postgis
    ports:
        - 8000:8000
    volumes:
        - .:/opt/imio_geonode/
    command: python manage.py runserver 0.0.0.0:8000
