postgis:
    build: Dockerfiles/postgis/
    hostname: postgis
    volumes:
        - ./postgres_data:/var/lib/postgresql

rabbitmq:
    image: rabbitmq
    hostname: rabbitmq-server
    ports:
        - "5672:5672"
        - "15672:15672"

geoserver:
    build: Dockerfiles/geoserver/
    hostname: geoserver
    links:
        - postgis
    ports:
        - 8080:8080
    volumes:
        - ./geoserver_data:/opt/geoserver/data_dir
geonode:
    build: .
    hostname: geonode
    links:
        - postgis
        - rabbitmq
    ports:
        - 8000:8000
    volumes:
        - .:/opt/imio_geonode/
    entrypoint:
        - /usr/bin/python
    command: manage.py runserver 0.0.0.0:8000

nginx:
    image: nginx:latest
    ports:
        - 80:80
    links:
        - geonode
        - geoserver
        - postgis
    volumes:
        - nginx-default.conf:/etc/nginx/conf.d/default.conf
