postgis:
    build: Dockerfiles/postgis/
    hostname: postgis
    volumes:
        - ./postgres_data:/var/lib/postgresql
    environment:
         - USERNAME=postgis
         - PASS=postgis
geoserver:
    build: Dockerfiles/geoserver/
    hostname: geoserver
    links:
        - postgis
        - geonode
    ports:
        - 8080:8080
    volumes:
        - ./geoserver_data:/opt/geoserver/data_dir
geonode:
    build: .
    hostname: geonode
    links:
        - postgis
    ports:
        - 8000:8000
    volumes:
        - .:/opt/imio_geonode/
    entrypoint: python
    command: manage.py runserver 0.0.0.0:8000
nginx:
    image: nginx:latest
    ports:
        - 80:80
    links:
        - geonode
        - geoserver
    volumes:
        - nginx-default.conf:/etc/nginx/conf.d/default.conf
